"""Add user_watch_states table

Revision ID: c7dc2f1e8518
Revises: 
Create Date: 2025-07-26 23:30:00.657122

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'c7dc2f1e8518'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_watch_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('blockchain', sa.String(length=50), nullable=False),
    sa.Column('watch_memos', sa.Boolean(), nullable=False),
    sa.Column('watch_events', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_watch_states_address'), 'user_watch_states', ['address'], unique=False)
    op.create_index(op.f('ix_user_watch_states_blockchain'), 'user_watch_states', ['blockchain'], unique=False)
    op.create_index(op.f('ix_user_watch_states_user_id'), 'user_watch_states', ['user_id'], unique=False)
    op.alter_column('crypto_addresses', 'message_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'crypto_addresses', 'users', ['memo_added_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'crypto_addresses', type_='foreignkey')
    op.alter_column('crypto_addresses', 'message_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_user_watch_states_user_id'), table_name='user_watch_states')
    op.drop_index(op.f('ix_user_watch_states_blockchain'), table_name='user_watch_states')
    op.drop_index(op.f('ix_user_watch_states_address'), table_name='user_watch_states')
    op.drop_table('user_watch_states')
    # ### end Alembic commands ###
